# SVD

In [1]:
import numpy as np

def svd(A):
    # Obliczenie macierzy kowariancji
    C = np.dot(A.T, A)
    
    # Znalezienie dominujących wektorów własnych macierzy kowariancji
    eigenvalues, eigenvectors = np.linalg.eigh(C)
    # Przekształcenie dominujących wektorów własnych na macierze ortogonalne U i V
    U = eigenvectors
    V = np.dot(A, U) / np.linalg.norm(np.dot(A, U), axis=0)
    
    # Obliczenie macierzy Sigma
    s = np.sqrt(np.abs(eigenvalues))
    Sigma = np.diag(sigma)
    
    return U, Sigma, V.T

In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]])
U, Sigma, Vt = svd(A)


In [14]:
print("Macierz U:")
print(U)
print("Macierz Sigma:")
print(Sigma)
print("Macierz V transponowane:")
print(Vt)
print("Macierz U*∑*V^T = A:")
print(U@Sigma@Vt)

Macierz U:
[[-0.78489445  0.61962948]
 [ 0.61962948  0.78489445]]
Macierz Sigma:
[[0.51430058 0.        ]
 [0.         9.52551809]]
Macierz V transponowane:
[[ 0.88346102  0.24078249 -0.40189603]
 [ 0.2298477   0.52474482  0.81964194]]
Macierz U*∑*V^T = A:
[[1. 3. 5.]
 [2. 4. 6.]]


In [4]:
U@Sigma@Vt

array([[1., 3., 5.],
       [2., 4., 6.]])