# SVD

In [1]:
import numpy as np

def svd(A):
    # Obliczenie macierzy kowariancji
    C = np.dot(A.T, A)
    
    # Znalezienie dominujących wektorów własnych macierzy kowariancji
    eigenvalues, eigenvectors = np.linalg.eigh(C)
    # Przekształcenie dominujących wektorów własnych na macierze ortogonalne U i V
    U = eigenvectors
    V = np.dot(A, U) / np.linalg.norm(np.dot(A, U), axis=0)
    
    # Obliczenie macierzy Sigma
    s = np.sqrt(np.abs(eigenvalues))
    Sigma = np.diag(sigma)
    
    return U, Sigma, V.T

In [15]:
A = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])

U, Sigma, Vt = svd(A)


In [16]:
print("Macierz U:")
print(U)
print("Macierz Sigma:")
print(Sigma)
print("Macierz V transponowane:")
print(Vt)
print("Macierz U*∑*V^T = A:")
print(U@Sigma@Vt)

Macierz U:
[[-7.07106781e-01  4.08248290e-01 -5.77350269e-01]
 [-2.22044605e-16 -8.16496581e-01 -5.77350269e-01]
 [ 7.07106781e-01  4.08248290e-01 -5.77350269e-01]]
Macierz Sigma:
[[ 3.46410162  0.          0.        ]
 [ 0.          6.92820323  0.        ]
 [ 0.          0.         15.        ]]
Macierz V transponowane:
[[-4.08248290e-01  8.16496581e-01 -4.08248290e-01]
 [-7.07106781e-01 -1.28197512e-16  7.07106781e-01]
 [-5.77350269e-01 -5.77350269e-01 -5.77350269e-01]]
Macierz U*∑*V^T = A:
[[4. 3. 8.]
 [9. 5. 1.]
 [2. 7. 6.]]


In [4]:
U@Sigma@Vt

array([[1., 3., 5.],
       [2., 4., 6.]])